### PR TITLE
Use checkstyle-check to fail build on warnings or errors

### LINKED ISSUE #8: Provide an option to fail the Checkstyle task if there are errors
Something like a setting checkstyleFailOnError (boolean) or checkstyleCheckSeverityLevel (string/enum) that can be set to fail a build if the code fails style checks.

### PR DESCRIPTION
**Pull request by JosephEarl**
Fixed #8. Ported from https://github.com/Redmart/sbt-checkstyle-plugin, refactored to avoid duplicate code.

Adds checkstyle-check task and checkstyleCheckSeverityLevel setting.

### CODE REVIEW

**Comment by JosephEarl** [comment]
Don't merge yet, just need to fix the empty project issue https://github.com/Redmart/sbt-checkstyle-plugin/issues/3 (and a test for it)

**Comment by JosephEarl** [comment]
I have fixed https://github.com/Redmart/sbt-checkstyle-plugin/issues/3 and https://github.com/Redmart/sbt-checkstyle-plugin/issues/4 as part of this port, but not https://github.com/Redmart/sbt-checkstyle-plugin/issues/5 yet.

**Comment by ajsquared** [comment]
Do you want to fix https://github.com/Redmart/sbt-checkstyle-plugin/issues/5 in this PR?

**Comment by JosephEarl** [comment]
Yes, let's do that

**Comment by ajsquared** [comment]
Great, sounds good!

**Comment by JosephEarl** [comment]
Fixed issue 5, please review

**Comment by ajsquared** [comment]
I really appreciate all the pull requests you've sent in!  I'm a bit busy this weekend, but I will look over everything on Monday.

File: src/main/scala/com/etsy/sbt/Checkstyle.scala [hunk 1]
```diff
@@ -10,56 +10,110 @@ import sbt._
...
+  * @author Alejandro Rivera <alejandro.rivera.lopez@gmail.com>
+  * @author Joseph Earl <joe@josephearl.co.uk>
   */
 object Checkstyle extends Plugin {
+
   import com.etsy.sbt.Checkstyle.CheckstyleTasks._
 
   object CheckstyleTasks {
     val checkstyle = TaskKey[Unit]("checkstyle", "Runs checkstyle")
+    val checkstyleCheck = TaskKey[Unit]("checkstyle-check", "Runs checkstyle and fails the task if issues are found")
```
Comment (ajsquared) [inline src/main/scala/com/etsy/sbt/Checkstyle.scala]: What do you think of of having a boolean setting that enables the feature of failing on issues rather than a separate task?  Alternatively `checkstyleCheckSeverityLevel` could be an `Option[String]` to enable/disable that behavior.

I'm not opposed to the current approach, just curious about your thoughts on doing it this way.

File: src/main/scala/com/etsy/sbt/Checkstyle.scala [hunk 2]
```diff
@@ -10,56 +10,110 @@ import sbt._
...
     val checkstyleTarget = SettingKey[File]("checkstyle-target", "The location of the generated checkstyle report")
     val checkstyleConfig = SettingKey[File]("checkstyle-config", "The location of the checkstyle configuration file")
     val xsltTransformations = SettingKey[Option[Set[XSLTSettings]]]("xslt-transformations", "An optional set of XSLT transformations to be applied to the checkstyle output")
+    val checkstyleCheckSeverityLevel = SettingKey[String]("checkstyle-check-level", "Sets the severity levels which should fail the build")
```
Comment (ajsquared) [inline src/main/scala/com/etsy/sbt/Checkstyle.scala]: What are your thoughts on defining an enum/case objects to enumerate the possible set of valid values here instead of using a string?

Comment (JosephEarl) [inline src/main/scala/com/etsy/sbt/Checkstyle.scala]: Sounds like a good idea

File: src/main/scala/com/etsy/sbt/Checkstyle.scala (hunk 1 above)
Comment (JosephEarl) [inline src/main/scala/com/etsy/sbt/Checkstyle.scala]: Yes maybe having checkstyleSeverityLevel as an Option[String] is a good idea and have it also use a single task

File: src/main/scala/com/etsy/sbt/Checkstyle.scala [hunk 3]
```diff
@@ -10,56 +10,110 @@ import sbt._
...
+            val errorMessage: String = error.attribute("message").get.head.text
+            log.error("Checkstyle " + severity + " found in " + filename + ":" + lineNumber + ": " + errorMessage)
+            issuesFound += 1
+          }
+        }
+      }
+
+      if (issuesFound > 0) {
+        log.error(issuesFound + " issue(s) found in Checkstyle report: " + outputFile + "")
+        sys.exit(1)
```
Comment (ajsquared) [inline src/main/scala/com/etsy/sbt/Checkstyle.scala]: I tend to prefer using `sys.error` to fail tasks.  If someone runs this interactively `sys.exit` will quit their SBT session.

Comment (JosephEarl) [inline src/main/scala/com/etsy/sbt/Checkstyle.scala]: See https://github.com/Redmart/sbt-checkstyle-plugin/commit/edc06a171267e396d18cef49a899f701b1f6ce0b for the reasoning

Comment (JosephEarl) [inline src/main/scala/com/etsy/sbt/Checkstyle.scala]: Happy to change it back if you are OK with having the stack trace in there

Comment (ajsquared) [inline src/main/scala/com/etsy/sbt/Checkstyle.scala]: Ah, this looks like a difference between the interactive and non-interactive modes.  When run interactively SBT will suppress the stacktrace from `sys.error`, but otherwise will not.  Unfortunately there doesn't seem to be an option for always suppressing the stack trace for a given task.

I don't mind the stack trace, but I can see how that would clutter the output.  If not having the stack trace would be better for you I'm fine with leaving this as-is.

**Comment by JosephEarl** [comment]
Updated to use Option[CheckstyleSeverityLevel] and removed the checkstyle-check task

**Comment by JosephEarl** [comment]
Maybe I should change it to just SeverityLevel - so importing `com.etsy.sbt.Checkstyle` requires `Checkstyle.SeverityLevel` to use.

File: src/main/scala/com/etsy/sbt/Checkstyle.scala [hunk 4]
```diff
@@ -10,56 +10,99 @@ import sbt._
...
-  *  
+  *
   * @author Andrew Johnson <ajohnson@etsy.com>
+  * @author Alejandro Rivera <alejandro.rivera.lopez@gmail.com>
+  * @author Joseph Earl <joe@josephearl.co.uk>
   */
 object Checkstyle extends Plugin {
-  import com.etsy.sbt.Checkstyle.CheckstyleTasks._
+
+  object CheckstyleSeverityLevel extends Enumeration {
```
Comment (ajsquared) [inline src/main/scala/com/etsy/sbt/Checkstyle.scala]: This looks good.  I did see your comment about using Checkstyle's built in SeverityLevel enum instead.  I'm happy with either choice there.
